export {default as Navbar} from "./navbar/Navbar"
export {default as Heading} from "./heading/Heading"
export {default as Footer} from "./footer/Footer"
export {default as Main} from "./main/Main"
export {default as Landing} from "./landing/Landing"
export {default as Project} from "./project/Project"
export {default as Contact} from "./contact/Contact"